### ISSUE TITLE
[Help] How to add additional information

### ISSUE THREAD

**Issue by krysalead** [vauxite-org/typescript-logging#39]
Hi,

I would like to inject dynamically a request ID into each log and not have to do that in every call to the logger but in a central place. I am using the Log4J style with 
```
const options = new LoggerFactoryOptions()
  .addLogGroupRule(
    new LogGroupRule(
      new RegExp('service.+'),
      LogLevel[config.getConfig().logging.services]
    )
  )
```
But I don't know, how to override the logger or change the message to add the information.

Thanks & regards

Olivier

**Comment by mreuvers** [comment]
Hello @krysalead ,

I am not entirely sure what you want to do, but I assume you mean to add some additional unique id to a log message?

You may want to check out:
https://github.com/mreuvers/typescript-logging/blob/master/docs/latest_log4j.md#formatting-message
and
https://github.com/mreuvers/typescript-logging/blob/master/docs/latest_log4j.md#custom-logger

The first allows you to change the message specifically, which is probably what you want. The second allows full control to change the loggers and message both.

Hope that helps!

**Comment by krysalead** [comment]
Hi,

Thanks it is more or less what I would need. Actually I have request id I want to see in all my logs to trace a transaction on my server. The issue with the proposed solution is that I need to add the full format of the log (level, date ...). I am using in a JS project Bunyan which allow to add extra data like the request id. Could be nice in a future release ;).

Thanks a lot for your library and your answer.

Olivier

**Comment by mreuvers** [comment]
Hello @krysalead 

Sorry for the delay, but thank you for the suggestion.

Just to be clear, you have some unique id you want to log during a transaction. Currently a message is logged by default something like: 

`2016-01-07 11:14:26,273 INFO [name] Some log text`

Where should the id be for each message, my feeling would be directly after [name] from the example above?

**Comment by mreuvers** [comment]
Closing this issue as it's very old, typescript logging 2 (major new version) has been released. Consider upgrading.
