### ISSUE TITLE
How I can download the logs file?

### ISSUE THREAD

**Issue by AmeerSalahinnova** [vauxite-org/typescript-logging#48]

**Comment by mreuvers** [comment]
Hi there,

There is no log file to download by default (after all it is logged to the browser console), you can either: 

- Get it from the console (if browsers support that)
- Write your custom logger, so you put it somewhere where you can get it.
- Use the chrome extension if you use "category style" logging.

**Comment by mreuvers** [comment]
Closing this issue as it's very old, typescript logging 2 (major new version) has been released. Consider upgrading.
